<?php
/*
 * This file is part of wulacms.
 *
 * (c) Leo Ning <windywany@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace wula\booky\search;

use TeamTNT\TNTSearch\Indexer\TNTIndexer;

class Indexer extends TNTIndexer {
    /**
     * @var \PDO
     */
    protected $index;

    public function createIndex($indexName) {
        $indexer = parent::createIndex($indexName); // TODO: Change the autogenerated stub
        $this->index->exec("CREATE TABLE IF NOT EXISTS filelist (
                    id INTEGER PRIMARY KEY,
                    file VARCHAR(64) NOT NULL,
                    title TEXT,
                    idx   INTEGER DEFAULT 0,  
                    atime INTEGER DEFAULT 0,
                    mtime INTEGER DEFAULT 0,
                    mtime1 INTEGER DEFAULT 0)");
        $this->index->exec("CREATE UNIQUE INDEX 'main'.'file' ON filelist ('file')");

        return $indexer;
    }

    /**
     * @return \PDO
     */
    public function getPdo() {
        return $this->index;
    }
}